<?php //Http definition of user form showing a table of users data ?>

<a href="/users/insert">Insert</a>
<table class="table table-striped">
<?php foreach ($users as $key => $user):?>
    <tr>
    <?php foreach ($user as $value):           
            if(is_array($value)):
                $value = implode(",", $value);?>
                <td><?=$value;?></td>           
        <?php else: ?> 
                <td><?=$value;?></td> 
    <?php   endif;                       
        endforeach;?>
        <td>
            <a href="/users/update/id/<?=$user['id'];?>">Update</a> | 
            <a href="/users/delete/id/<?=$user['id'];?>">Delete</a>
        </td>
   </tr>
<?php endforeach;?>
</table>
